import { MultiLanguageText } from '../language';
import {
  MainMaterialCategoryType,
  MainMaterialPerformanceStandardValue,
  MainMaterialType,
} from './type';

// TODO: check on game
export const MainMaterialsMap: {
  categoryType: MainMaterialCategoryType;
  type: MainMaterialType;
  name: MultiLanguageText;
  standardValue: MainMaterialPerformanceStandardValue;
}[] = [
  // Metal
  {
    categoryType: 'Metal',
    type: 'MenosBronze',
    name: {
      en: 'MenosBronze',
      ja: '',
    },
    standardValue: {
      sharp: 10,
      heavy: 10,
      force: 10,
      tech: 10,
      strike: 10,
      slash: 10,
      thrust: 10,
      magic: 10,
    },
  },
  {
    categoryType: 'Metal',
    type: 'ForsenaIron',
    name: {
      en: 'ForsenaIron',
      ja: '',
    },
    standardValue: {
      sharp: 15,
      heavy: 15,
      force: 15,
      tech: 15,
      strike: 15,
      slash: 15,
      thrust: 15,
      magic: 15,
    },
  },
  {
    categoryType: 'Metal',
    type: 'GranzSteel',
    name: {
      en: 'GranzSteel',
      ja: '',
    },
    standardValue: {
      sharp: 20,
      heavy: 20,
      force: 20,
      tech: 20,
      strike: 20,
      slash: 20,
      thrust: 20,
      magic: 20,
    },
  },
  {
    categoryType: 'Metal',
    type: 'Mythril Silver',
    name: {
      en: 'Mythril',
      ja: '',
    },
    standardValue: {
      sharp: 25,
      heavy: 25,
      force: 25,
      tech: 25,
      strike: 25,
      slash: 25,
      thrust: 25,
      magic: 25,
    },
  },
  {
    categoryType: 'Metal',
    type: 'Astoria Silver',
    name: {
      en: 'Astoria',
      ja: '',
    },
    standardValue: {
      sharp: 30,
      heavy: 30,
      force: 30,
      tech: 30,
      strike: 30,
      slash: 30,
      thrust: 30,
      magic: 30,
    },
  },
  {
    categoryType: 'Metal',
    type: 'VizelGold',
    name: {
      en: 'VizelGold',
      ja: '',
    },
    standardValue: {
      sharp: 35,
      heavy: 35,
      force: 35,
      tech: 35,
      strike: 35,
      slash: 35,
      thrust: 35,
      magic: 35,
    },
  },
  {
    categoryType: 'Metal',
    type: 'IshePlatinum',
    name: {
      en: 'IshePlatinum',
      ja: '',
    },
    standardValue: {
      sharp: 40,
      heavy: 40,
      force: 40,
      tech: 40,
      strike: 40,
      slash: 40,
      thrust: 40,
      magic: 40,
    },
  },
  {
    categoryType: 'Metal',
    type: 'LorimarIron',
    name: {
      en: 'LorimarIron',
      ja: '',
    },
    standardValue: {
      sharp: 45,
      heavy: 45,
      force: 45,
      tech: 45,
      strike: 45,
      slash: 45,
      thrust: 45,
      magic: 45,
    },
  },
  {
    categoryType: 'Metal',
    type: 'AltenaAlloy',
    name: {
      en: 'AltenaAlloy',
      ja: '',
    },
    standardValue: {
      sharp: 50,
      heavy: 50,
      force: 50,
      tech: 50,
      strike: 50,
      slash: 50,
      thrust: 50,
      magic: 50,
    },
  },
  {
    categoryType: 'Metal',
    type: 'MaiaLead',
    name: {
      en: 'MaiaLead',
      ja: '',
    },
    standardValue: {
      sharp: 36,
      heavy: 3,
      force: 68,
      tech: 18,
      strike: 3,
      slash: 18,
      thrust: 36,
      magic: 36,
    },
  },
  {
    categoryType: 'Metal',
    type: 'Orihalcon',
    name: {
      en: 'Orihalcon',
      ja: '',
    },
    standardValue: {
      sharp: 28,
      heavy: 28,
      force: 28,
      tech: 28,
      strike: 28,
      slash: 28,
      thrust: 28,
      magic: 28,
    },
  },
  // Wood
  {
    categoryType: 'Wood',
    type: 'OakWood',
    name: {
      en: 'OakWood',
      ja: '',
    },
    standardValue: {
      sharp: 10,
      heavy: 6,
      force: 14,
      tech: 4,
      strike: 16,
      slash: 5,
      thrust: 7,
      magic: 9,
    },
  },
  {
    categoryType: 'Wood',
    type: 'HollyWood',
    name: {
      en: 'HollyWood',
      ja: '',
    },
    standardValue: {
      sharp: 15,
      heavy: 9,
      force: 21,
      tech: 6,
      strike: 24,
      slash: 7,
      thrust: 10,
      magic: 13,
    },
  },
  {
    categoryType: 'Wood',
    type: 'BaobabWood',
    name: {
      en: 'BaobabWood',
      ja: '',
    },
    standardValue: {
      sharp: 20,
      heavy: 12,
      force: 28,
      tech: 8,
      strike: 32,
      slash: 10,
      thrust: 14,
      magic: 18,
    },
  },
  {
    categoryType: 'Wood',
    type: 'EbonyWood',
    name: {
      en: 'EbonyWood',
      ja: '',
    },
    standardValue: {
      sharp: 25,
      heavy: 15,
      force: 35,
      tech: 10,
      strike: 40,
      slash: 12,
      thrust: 17,
      magic: 22,
    },
  },
  {
    categoryType: 'Wood',
    type: 'Ashe Wood',
    name: {
      en: 'Ashe',
      ja: '',
    },
    standardValue: {
      sharp: 35,
      heavy: 21,
      force: 49,
      tech: 14,
      strike: 56,
      slash: 17,
      thrust: 24,
      magic: 31,
    },
  },
  {
    categoryType: 'Wood',
    type: 'DiorWood',
    name: {
      en: 'DiorWood',
      ja: '',
    },
    standardValue: {
      sharp: 50,
      heavy: 30,
      force: 70,
      tech: 20,
      strike: 80,
      slash: 25,
      thrust: 35,
      magic: 45,
    },
  },
  {
    categoryType: 'Wood',
    type: 'Mistletoe Wood',
    name: {
      en: 'Mistletoe',
      ja: '',
    },
    standardValue: {
      sharp: 30,
      heavy: 18,
      force: 42,
      tech: 12,
      strike: 48,
      slash: 15,
      thrust: 21,
      magic: 27,
    },
  },
  {
    categoryType: 'Wood',
    type: 'FossilWood',
    name: {
      en: 'FossilWood',
      ja: '',
    },
    standardValue: {
      sharp: 40,
      heavy: 24,
      force: 56,
      tech: 16,
      strike: 64,
      slash: 20,
      thrust: 28,
      magic: 36,
    },
  },
  // Stone
  {
    categoryType: 'Stone',
    type: 'Marble',
    name: {
      en: 'Marble',
      ja: '',
    },
    standardValue: {
      sharp: 12,
      heavy: 2,
      force: 21,
      tech: 16,
      strike: 7,
      slash: 9,
      thrust: 12,
      magic: 15,
    },
  },
  {
    categoryType: 'Stone',
    type: 'Obsidian',
    name: {
      en: 'Obsidian',
      ja: '',
    },
    standardValue: {
      sharp: 24,
      heavy: 4,
      force: 43,
      tech: 33,
      strike: 14,
      slash: 18,
      thrust: 24,
      magic: 30,
    },
  },
  {
    categoryType: 'Stone',
    type: 'PedanStone',
    name: {
      en: 'PedanStone',
      ja: '',
    },
    standardValue: {
      sharp: 36,
      heavy: 7,
      force: 64,
      tech: 50,
      strike: 21,
      slash: 27,
      thrust: 36,
      magic: 45,
    },
  },
  {
    categoryType: 'Stone',
    type: "Gaeus'sTears",
    name: {
      en: 'Gaeus',
      ja: '',
    },
    standardValue: {
      sharp: 48,
      heavy: 9,
      force: 86,
      tech: 67,
      strike: 28,
      slash: 36,
      thrust: 48,
      magic: 60,
    },
  },
  // Hide
  {
    categoryType: 'Hide',
    type: 'AnimalHide',
    name: {
      en: 'AnimalHide',
      ja: '',
    },
    standardValue: {
      sharp: 10,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 20,
      slash: 8,
      thrust: 12,
      magic: 10,
    },
  },
  {
    categoryType: 'Hide',
    type: 'GatorSkin',
    name: {
      en: 'GatorSkin',
      ja: '',
    },
    standardValue: {
      sharp: 18,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 36,
      slash: 14,
      thrust: 21,
      magic: 18,
    },
  },
  {
    categoryType: 'Hide',
    type: 'CentaurHide',
    name: {
      en: 'CentaurHide',
      ja: '',
    },
    standardValue: {
      sharp: 26,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 52,
      slash: 20,
      thrust: 31,
      magic: 26,
    },
  },
  {
    categoryType: 'Hide',
    type: 'DragonSkin',
    name: {
      en: 'DragonSkin',
      ja: '',
    },
    standardValue: {
      sharp: 35,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 70,
      slash: 28,
      thrust: 42,
      magic: 35,
    },
  },
  // Scales
  {
    categoryType: 'Scales',
    type: 'FishScales',
    name: {
      en: 'FishScales',
      ja: '',
    },
    standardValue: {
      sharp: 8,
      heavy: 8,
      force: 7,
      tech: 7,
      strike: 9,
      slash: 9,
      thrust: 8,
      magic: 4,
    },
  },
  {
    categoryType: 'Scales',
    type: 'LizardScales',
    name: {
      en: 'LizardScales',
      ja: '',
    },
    standardValue: {
      sharp: 16,
      heavy: 17,
      force: 14,
      tech: 14,
      strike: 19,
      slash: 19,
      thrust: 16,
      magic: 8,
    },
  },
  {
    categoryType: 'Scales',
    type: 'SnakeScales',
    name: {
      en: 'SnakeScales',
      ja: '',
    },
    standardValue: {
      sharp: 24,
      heavy: 26,
      force: 21,
      tech: 21,
      strike: 28,
      slash: 28,
      thrust: 24,
      magic: 12,
    },
  },
  {
    categoryType: 'Scales',
    type: 'DragonScales',
    name: {
      en: 'DragonScales',
      ja: '',
    },
    standardValue: {
      sharp: 60,
      heavy: 66,
      force: 54,
      tech: 54,
      strike: 72,
      slash: 72,
      thrust: 60,
      magic: 30,
    },
  },
  // Bone
  {
    categoryType: 'Bone',
    type: 'AnimalBone',
    name: {
      en: 'AnimalBone',
      ja: '',
    },
    standardValue: {
      sharp: 14,
      heavy: 10,
      force: 12,
      tech: 12,
      strike: 9,
      slash: 15,
      thrust: 6,
      magic: 9,
    },
  },
  {
    categoryType: 'Bone',
    type: 'Ivory',
    name: {
      en: 'Ivory',
      ja: '',
    },
    standardValue: {
      sharp: 28,
      heavy: 21,
      force: 24,
      tech: 24,
      strike: 18,
      slash: 30,
      thrust: 12,
      magic: 18,
    },
  },
  {
    categoryType: 'Bone',
    type: 'CursedBone',
    name: {
      en: 'CursedBone',
      ja: '',
    },
    standardValue: {
      sharp: 43,
      heavy: 32,
      force: 36,
      tech: 36,
      strike: 27,
      slash: 45,
      thrust: 18,
      magic: 27,
    },
  },
  {
    categoryType: 'Bone',
    type: 'Fossil',
    name: {
      en: 'Fossil',
      ja: '',
    },
    standardValue: {
      sharp: 57,
      heavy: 43,
      force: 48,
      tech: 48,
      strike: 36,
      slash: 60,
      thrust: 24,
      magic: 36,
    },
  },
  // Fabric
  {
    categoryType: 'Fabric',
    type: 'ToppleCotton',
    name: {
      en: 'ToppleCotton',
      ja: '',
    },
    standardValue: {
      sharp: 18,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 9,
      slash: 9,
      thrust: 9,
      magic: 9,
    },
  },
  {
    categoryType: 'Fabric',
    type: "Sultan'sSilk",
    name: {
      en: 'Sultan',
      ja: '',
    },
    standardValue: {
      sharp: 28,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 14,
      slash: 14,
      thrust: 14,
      magic: 14,
    },
  },
  {
    categoryType: 'Fabric',
    type: 'JuddHemp',
    name: {
      en: 'JuddHemp',
      ja: '',
    },
    standardValue: {
      sharp: 38,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 19,
      slash: 19,
      thrust: 19,
      magic: 19,
    },
  },
  {
    categoryType: 'Fabric',
    type: 'AltenaFelt',
    name: {
      en: 'AltenaFelt',
      ja: '',
    },
    standardValue: {
      sharp: 48,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 24,
      slash: 24,
      thrust: 24,
      magic: 24,
    },
  },
  // Aerolite
  {
    categoryType: 'Aerolite',
    type: 'JacobiniRock',
    name: {
      en: 'JacobiniRock',
      ja: '',
    },
    standardValue: {
      sharp: 15,
      heavy: 11,
      force: 22,
      tech: 24,
      strike: 15,
      slash: 13,
      thrust: 18,
      magic: 24,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'HalleyRock',
    name: {
      en: 'HalleyRock',
      ja: '',
    },
    standardValue: {
      sharp: 20,
      heavy: 15,
      force: 30,
      tech: 32,
      strike: 20,
      slash: 18,
      thrust: 24,
      magic: 32,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'AnkhRock',
    name: {
      en: 'AnkhRock',
      ja: '',
    },
    standardValue: {
      sharp: 25,
      heavy: 18,
      force: 37,
      tech: 40,
      strike: 25,
      slash: 22,
      thrust: 30,
      magic: 40,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'VinekRock',
    name: {
      en: 'VinekRock',
      ja: '',
    },
    standardValue: {
      sharp: 30,
      heavy: 22,
      force: 45,
      tech: 48,
      strike: 30,
      slash: 27,
      thrust: 36,
      magic: 48,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'TuttleRock',
    name: {
      en: 'TuttleRock',
      ja: '',
    },
    standardValue: {
      sharp: 35,
      heavy: 26,
      force: 52,
      tech: 56,
      strike: 35,
      slash: 31,
      thrust: 42,
      magic: 56,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'NemesisRock',
    name: {
      en: 'NemesisRock',
      ja: '',
    },
    standardValue: {
      sharp: 40,
      heavy: 30,
      force: 60,
      tech: 64,
      strike: 40,
      slash: 36,
      thrust: 48,
      magic: 64,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'BiellaRock',
    name: {
      en: 'BiellaRock',
      ja: '',
    },
    standardValue: {
      sharp: 45,
      heavy: 33,
      force: 67,
      tech: 72,
      strike: 45,
      slash: 40,
      thrust: 54,
      magic: 72,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'SwifteRock',
    name: {
      en: 'SwifteRock',
      ja: '',
    },
    standardValue: {
      sharp: 50,
      heavy: 37,
      force: 75,
      tech: 80,
      strike: 50,
      slash: 45,
      thrust: 60,
      magic: 80,
    },
  },
  // Miscellaneous
  {
    categoryType: 'Miscellaneous',
    type: 'Adamantite',
    name: {
      en: 'Adamantite',
      ja: '',
    },
    standardValue: {
      sharp: 62,
      heavy: 46,
      force: 93,
      tech: 99,
      strike: 62,
      slash: 31,
      thrust: 93,
      magic: 62,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'Fullmetal',
    name: {
      en: 'Fullmetal',
      ja: '',
    },
    standardValue: {
      sharp: 55,
      heavy: 41,
      force: 68,
      tech: 66,
      strike: 44,
      slash: 27,
      thrust: 99,
      magic: 27,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'Coral',
    name: {
      en: 'Coral',
      ja: '',
    },
    standardValue: {
      sharp: 18,
      heavy: 21,
      force: 14,
      tech: 12,
      strike: 23,
      slash: 9,
      thrust: 32,
      magic: 9,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'TortoiseShell',
    name: {
      en: 'TortoiseShell',
      ja: '',
    },
    standardValue: {
      sharp: 26,
      heavy: 31,
      force: 20,
      tech: 18,
      strike: 33,
      slash: 13,
      thrust: 46,
      magic: 13,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'Shell',
    name: {
      en: 'Shell',
      ja: '',
    },
    standardValue: {
      sharp: 20,
      heavy: 24,
      force: 16,
      tech: 14,
      strike: 26,
      slash: 10,
      thrust: 36,
      magic: 10,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'Emerald',
    name: {
      en: 'Emerald',
      ja: '',
    },
    standardValue: {
      sharp: 2,
      heavy: 2,
      force: 2,
      tech: 2,
      strike: 1,
      slash: 1,
      thrust: 1,
      magic: 50,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'Pearl',
    name: {
      en: 'Pearl',
      ja: '',
    },
    standardValue: {
      sharp: 2,
      heavy: 2,
      force: 2,
      tech: 2,
      strike: 1,
      slash: 1,
      thrust: 1,
      magic: 50,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'LapisLazuli',
    name: {
      en: 'LapisLazuli',
      ja: '',
    },
    standardValue: {
      sharp: 2,
      heavy: 2,
      force: 2,
      tech: 2,
      strike: 1,
      slash: 1,
      thrust: 1,
      magic: 50,
    },
  },
] as const;
