import { ElementType } from '../element';
import { MultiLanguageText } from '../language';
import {
  MainMaterialCategoryType,
  MainMaterialPerformanceStandardValue,
  MainMaterialType,
} from './type';

export type MainMaterial = {
  categoryType: MainMaterialCategoryType;
  type: MainMaterialType;
  suppressionValue: number;
  name: MultiLanguageText;
  standardValue: MainMaterialPerformanceStandardValue;
  elementResist: { [key in ElementType]: number };
};

export const AllMainMaterials: MainMaterial[] = [
  // Metal
  {
    categoryType: 'Metal',
    type: 'MenosBronze',
    suppressionValue: 18,
    name: {
      en: 'MenosBronze',
      ja: 'メノス銅',
    },
    standardValue: {
      sharp: 10,
      heavy: 10,
      force: 10,
      tech: 10,
      strike: 10,
      slash: 10,
      thrust: 10,
      magic: 10,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 8,
      jinn: 8,
      undine: 8,
    },
  },
  {
    categoryType: 'Metal',
    type: 'ForsenaIron',
    suppressionValue: 20,
    name: {
      en: 'ForsenaIron',
      ja: 'フォルセナ鉄',
    },
    standardValue: {
      sharp: 15,
      heavy: 15,
      force: 15,
      tech: 15,
      strike: 15,
      slash: 15,
      thrust: 15,
      magic: 15,
    },
    elementResist: {
      wisp: 9,
      shade: 9,
      dryad: 9,
      aura: 9,
      salamander: 9,
      gnome: 9,
      jinn: 9,
      undine: 9,
    },
  },
  {
    categoryType: 'Metal',
    type: 'GranzSteel',
    suppressionValue: 24,
    name: {
      en: 'GranzSteel',
      ja: 'グランス鋼鉄',
    },
    standardValue: {
      sharp: 20,
      heavy: 20,
      force: 20,
      tech: 20,
      strike: 20,
      slash: 20,
      thrust: 20,
      magic: 20,
    },
    elementResist: {
      wisp: 9,
      shade: 9,
      dryad: 9,
      aura: 9,
      salamander: 9,
      gnome: 9,
      jinn: 9,
      undine: 9,
    },
  },
  {
    categoryType: 'Metal',
    type: 'Mythril Silver',
    suppressionValue: 12,
    name: {
      en: 'Mythril',
      ja: 'ミスリル銀',
    },
    standardValue: {
      sharp: 25,
      heavy: 25,
      force: 25,
      tech: 25,
      strike: 25,
      slash: 25,
      thrust: 25,
      magic: 25,
    },
    elementResist: {
      wisp: 8,
      shade: 6,
      dryad: 7,
      aura: 7,
      salamander: 7,
      gnome: 7,
      jinn: 7,
      undine: 7,
    },
  },
  {
    categoryType: 'Metal',
    type: 'Astoria Silver',
    suppressionValue: 16,
    name: {
      en: 'Astoria',
      ja: 'アストリア銀',
    },
    standardValue: {
      sharp: 30,
      heavy: 30,
      force: 30,
      tech: 30,
      strike: 30,
      slash: 30,
      thrust: 30,
      magic: 30,
    },
    elementResist: {
      wisp: 9,
      shade: 7,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 8,
      jinn: 8,
      undine: 8,
    },
  },
  {
    categoryType: 'Metal',
    type: 'VizelGold',
    suppressionValue: 16,
    name: {
      en: 'VizelGold',
      ja: 'バイゼル金',
    },
    standardValue: {
      sharp: 35,
      heavy: 35,
      force: 35,
      tech: 35,
      strike: 35,
      slash: 35,
      thrust: 35,
      magic: 35,
    },
    elementResist: {
      wisp: 7,
      shade: 9,
      dryad: 9,
      aura: 9,
      salamander: 9,
      gnome: 9,
      jinn: 9,
      undine: 9,
    },
  },
  {
    categoryType: 'Metal',
    type: 'IshePlatinum',
    suppressionValue: 16,
    name: {
      en: 'IshePlatinum',
      ja: 'イシュ白金',
    },
    standardValue: {
      sharp: 40,
      heavy: 40,
      force: 40,
      tech: 40,
      strike: 40,
      slash: 40,
      thrust: 40,
      magic: 40,
    },
    elementResist: {
      wisp: 7,
      shade: 7,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 8,
      jinn: 8,
      undine: 8,
    },
  },
  {
    categoryType: 'Metal',
    type: 'LorimarIron',
    suppressionValue: 16,
    name: {
      en: 'LorimarIron',
      ja: 'ロリマー聖鉄',
    },
    standardValue: {
      sharp: 45,
      heavy: 45,
      force: 45,
      tech: 45,
      strike: 45,
      slash: 45,
      thrust: 45,
      magic: 45,
    },
    elementResist: {
      wisp: 7,
      shade: 9,
      dryad: 9,
      aura: 9,
      salamander: 9,
      gnome: 9,
      jinn: 9,
      undine: 9,
    },
  },
  {
    categoryType: 'Metal',
    type: 'AltenaAlloy',
    suppressionValue: 18,
    name: {
      en: 'AltenaAlloy',
      ja: 'アルテナ合金',
    },
    standardValue: {
      sharp: 50,
      heavy: 50,
      force: 50,
      tech: 50,
      strike: 50,
      slash: 50,
      thrust: 50,
      magic: 50,
    },
    elementResist: {
      wisp: 10,
      shade: 10,
      dryad: 10,
      aura: 10,
      salamander: 10,
      gnome: 10,
      jinn: 10,
      undine: 10,
    },
  },
  {
    categoryType: 'Metal',
    type: 'MaiaLead',
    suppressionValue: 48,
    name: {
      en: 'MaiaLead',
      ja: 'マイア鉛',
    },
    standardValue: {
      sharp: 36,
      heavy: 3,
      force: 68,
      tech: 18,
      strike: 3,
      slash: 18,
      thrust: 36,
      magic: 36,
    },
    elementResist: {
      wisp: 32,
      shade: 32,
      dryad: 32,
      aura: 32,
      salamander: 32,
      gnome: 32,
      jinn: 32,
      undine: 32,
    },
  },
  {
    categoryType: 'Metal',
    type: 'Orihalcon',
    suppressionValue: 12,
    name: {
      en: 'Orihalcon',
      ja: 'オリハルコン',
    },
    standardValue: {
      sharp: 28,
      heavy: 28,
      force: 28,
      tech: 28,
      strike: 28,
      slash: 28,
      thrust: 28,
      magic: 28,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 7,
      aura: 10,
      salamander: 7,
      gnome: 9,
      jinn: 6,
      undine: 8,
    },
  },
  // Wood
  {
    categoryType: 'Wood',
    type: 'OakWood',
    suppressionValue: 16,
    name: {
      en: 'OakWood',
      ja: 'かしの木',
    },
    standardValue: {
      sharp: 10,
      heavy: 6,
      force: 14,
      tech: 4,
      strike: 16,
      slash: 5,
      thrust: 7,
      magic: 9,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 6,
      aura: 9,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 7,
    },
  },
  {
    categoryType: 'Wood',
    type: 'HollyWood',
    suppressionValue: 14,
    name: {
      en: 'HollyWood',
      ja: 'ひいらぎの木',
    },
    standardValue: {
      sharp: 15,
      heavy: 9,
      force: 21,
      tech: 6,
      strike: 24,
      slash: 7,
      thrust: 10,
      magic: 13,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 6,
      aura: 9,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 7,
    },
  },
  {
    categoryType: 'Wood',
    type: 'BaobabWood',
    suppressionValue: 24,
    name: {
      en: 'BaobabWood',
      ja: 'バオバブの木',
    },
    standardValue: {
      sharp: 20,
      heavy: 12,
      force: 28,
      tech: 8,
      strike: 32,
      slash: 10,
      thrust: 14,
      magic: 18,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 6,
      aura: 9,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 7,
    },
  },
  {
    categoryType: 'Wood',
    type: 'EbonyWood',
    suppressionValue: 24,
    name: {
      en: 'EbonyWood',
      ja: '黒檀',
    },
    standardValue: {
      sharp: 25,
      heavy: 15,
      force: 35,
      tech: 10,
      strike: 40,
      slash: 12,
      thrust: 17,
      magic: 22,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 6,
      aura: 9,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 7,
    },
  },
  {
    categoryType: 'Wood',
    type: 'Ashe Wood',
    suppressionValue: 12,
    name: {
      en: 'Ashe',
      ja: 'トネリコの木',
    },
    standardValue: {
      sharp: 35,
      heavy: 21,
      force: 49,
      tech: 14,
      strike: 56,
      slash: 17,
      thrust: 24,
      magic: 31,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 6,
      aura: 9,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 7,
    },
  },
  {
    categoryType: 'Wood',
    type: 'DiorWood',
    suppressionValue: 10,
    name: {
      en: 'DiorWood',
      ja: 'ディオールの木',
    },
    standardValue: {
      sharp: 50,
      heavy: 30,
      force: 70,
      tech: 20,
      strike: 80,
      slash: 25,
      thrust: 35,
      magic: 45,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 5,
      aura: 9,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 7,
    },
  },
  {
    categoryType: 'Wood',
    type: 'Mistletoe Wood',
    suppressionValue: 11,
    name: {
      en: 'Mistletoe',
      ja: 'やどりぎ',
    },
    standardValue: {
      sharp: 30,
      heavy: 18,
      force: 42,
      tech: 12,
      strike: 48,
      slash: 15,
      thrust: 21,
      magic: 27,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 6,
      aura: 9,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 7,
    },
  },
  {
    categoryType: 'Wood',
    type: 'FossilWood',
    suppressionValue: 22,
    name: {
      en: 'FossilWood',
      ja: '化石樹',
    },
    standardValue: {
      sharp: 40,
      heavy: 24,
      force: 56,
      tech: 16,
      strike: 64,
      slash: 20,
      thrust: 28,
      magic: 36,
    },
    elementResist: {
      wisp: 7,
      shade: 6,
      dryad: 6,
      aura: 9,
      salamander: 10,
      gnome: 6,
      jinn: 7,
      undine: 7,
    },
  },
  // Stone
  {
    categoryType: 'Stone',
    type: 'Marble',
    suppressionValue: 28,
    name: {
      en: 'Marble',
      ja: '大理石',
    },
    standardValue: {
      sharp: 12,
      heavy: 2,
      force: 21,
      tech: 16,
      strike: 7,
      slash: 9,
      thrust: 12,
      magic: 15,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 9,
      aura: 7,
      salamander: 7,
      gnome: 6,
      jinn: 10,
      undine: 7,
    },
  },
  {
    categoryType: 'Stone',
    type: 'Obsidian',
    suppressionValue: 32,
    name: {
      en: 'Obsidian',
      ja: '黒曜石',
    },
    standardValue: {
      sharp: 24,
      heavy: 4,
      force: 43,
      tech: 33,
      strike: 14,
      slash: 18,
      thrust: 24,
      magic: 30,
    },
    elementResist: {
      wisp: 8,
      shade: 6,
      dryad: 9,
      aura: 7,
      salamander: 7,
      gnome: 6,
      jinn: 10,
      undine: 8,
    },
  },
  {
    categoryType: 'Stone',
    type: 'PedanStone',
    suppressionValue: 24,
    name: {
      en: 'PedanStone',
      ja: 'ペダン石',
    },
    standardValue: {
      sharp: 36,
      heavy: 7,
      force: 64,
      tech: 50,
      strike: 21,
      slash: 27,
      thrust: 36,
      magic: 45,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 9,
      aura: 7,
      salamander: 7,
      gnome: 7,
      jinn: 11,
      undine: 7,
    },
  },
  {
    categoryType: 'Stone',
    type: "Gaeus'sTears",
    suppressionValue: 20,
    name: {
      en: 'Gaeus',
      ja: 'ガイアの涙',
    },
    standardValue: {
      sharp: 48,
      heavy: 9,
      force: 86,
      tech: 67,
      strike: 28,
      slash: 36,
      thrust: 48,
      magic: 60,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 9,
      aura: 7,
      salamander: 10,
      gnome: 6,
      jinn: 10,
      undine: 6,
    },
  },
  // Hide
  {
    categoryType: 'Hide',
    type: 'AnimalHide',
    suppressionValue: 8,
    name: {
      en: 'AnimalHide',
      ja: '獣の革',
    },
    standardValue: {
      sharp: 10,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 20,
      slash: 8,
      thrust: 12,
      magic: 10,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 7,
      aura: 9,
      salamander: 9,
      gnome: 7,
      jinn: 7,
      undine: 7,
    },
  },
  {
    categoryType: 'Hide',
    type: 'GatorSkin',
    suppressionValue: 12,
    name: {
      en: 'GatorSkin',
      ja: 'ワニ革',
    },
    standardValue: {
      sharp: 18,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 36,
      slash: 14,
      thrust: 21,
      magic: 18,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 7,
      aura: 9,
      salamander: 9,
      gnome: 8,
      jinn: 8,
      undine: 6,
    },
  },
  {
    categoryType: 'Hide',
    type: 'CentaurHide',
    suppressionValue: 20,
    name: {
      en: 'CentaurHide',
      ja: '鉄甲獣の革　※',
    },
    standardValue: {
      sharp: 26,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 52,
      slash: 20,
      thrust: 31,
      magic: 26,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 9,
      aura: 7,
      salamander: 8,
      gnome: 7,
      jinn: 8,
      undine: 8,
    },
  },
  {
    categoryType: 'Hide',
    type: 'DragonSkin',
    suppressionValue: 20,
    name: {
      en: 'DragonSkin',
      ja: '飛竜の革',
    },
    standardValue: {
      sharp: 35,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 70,
      slash: 28,
      thrust: 42,
      magic: 35,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 7,
      aura: 9,
      salamander: 5,
      gnome: 10,
      jinn: 5,
      undine: 10,
    },
  },
  // Scales
  {
    categoryType: 'Scales',
    type: 'FishScales',
    suppressionValue: 20,
    name: {
      en: 'FishScales',
      ja: '魚鱗',
    },
    standardValue: {
      sharp: 8,
      heavy: 8,
      force: 7,
      tech: 7,
      strike: 9,
      slash: 9,
      thrust: 8,
      magic: 4,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 8,
      jinn: 8,
      undine: 6,
    },
  },
  {
    categoryType: 'Scales',
    type: 'LizardScales',
    suppressionValue: 20,
    name: {
      en: 'LizardScales',
      ja: 'トカゲの鱗',
    },
    standardValue: {
      sharp: 16,
      heavy: 17,
      force: 14,
      tech: 14,
      strike: 19,
      slash: 19,
      thrust: 16,
      magic: 8,
    },
    elementResist: {
      wisp: 7,
      shade: 9,
      dryad: 8,
      aura: 8,
      salamander: 7,
      gnome: 8,
      jinn: 8,
      undine: 9,
    },
  },
  {
    categoryType: 'Scales',
    type: 'SnakeScales',
    suppressionValue: 20,
    name: {
      en: 'SnakeScales',
      ja: 'ヘビの鱗',
    },
    standardValue: {
      sharp: 24,
      heavy: 26,
      force: 21,
      tech: 21,
      strike: 28,
      slash: 28,
      thrust: 24,
      magic: 12,
    },
    elementResist: {
      wisp: 9,
      shade: 7,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 7,
      jinn: 8,
      undine: 7,
    },
  },
  {
    categoryType: 'Scales',
    type: 'DragonScales',
    suppressionValue: 14,
    name: {
      en: 'DragonScales',
      ja: '竜鱗',
    },
    standardValue: {
      sharp: 60,
      heavy: 66,
      force: 54,
      tech: 54,
      strike: 72,
      slash: 72,
      thrust: 60,
      magic: 30,
    },
    elementResist: {
      wisp: 7,
      shade: 7,
      dryad: 7,
      aura: 7,
      salamander: 6,
      gnome: 7,
      jinn: 7,
      undine: 7,
    },
  },
  // Bone
  {
    categoryType: 'Bone',
    type: 'AnimalBone',
    suppressionValue: 20,
    name: {
      en: 'AnimalBone',
      ja: '獣の骨',
    },
    standardValue: {
      sharp: 14,
      heavy: 10,
      force: 12,
      tech: 12,
      strike: 9,
      slash: 15,
      thrust: 6,
      magic: 9,
    },
    elementResist: {
      wisp: 9,
      shade: 6,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 8,
      jinn: 8,
      undine: 8,
    },
  },
  {
    categoryType: 'Bone',
    type: 'Ivory',
    suppressionValue: 20,
    name: {
      en: 'Ivory',
      ja: '象牙',
    },
    standardValue: {
      sharp: 28,
      heavy: 21,
      force: 24,
      tech: 24,
      strike: 18,
      slash: 30,
      thrust: 12,
      magic: 18,
    },
    elementResist: {
      wisp: 7,
      shade: 6,
      dryad: 7,
      aura: 7,
      salamander: 8,
      gnome: 6,
      jinn: 7,
      undine: 7,
    },
  },
  {
    categoryType: 'Bone',
    type: 'CursedBone',
    suppressionValue: 36,
    name: {
      en: 'CursedBone',
      ja: '呪われた骨',
    },
    standardValue: {
      sharp: 43,
      heavy: 32,
      force: 36,
      tech: 36,
      strike: 27,
      slash: 45,
      thrust: 18,
      magic: 27,
    },
    elementResist: {
      wisp: 9,
      shade: 5,
      dryad: 9,
      aura: 7,
      salamander: 9,
      gnome: 7,
      jinn: 9,
      undine: 7,
    },
  },
  {
    categoryType: 'Bone',
    type: 'Fossil',
    suppressionValue: 20,
    name: {
      en: 'Fossil',
      ja: '化石',
    },
    standardValue: {
      sharp: 57,
      heavy: 43,
      force: 48,
      tech: 48,
      strike: 36,
      slash: 60,
      thrust: 24,
      magic: 36,
    },
    elementResist: {
      wisp: 9,
      shade: 6,
      dryad: 8,
      aura: 8,
      salamander: 10,
      gnome: 6,
      jinn: 10,
      undine: 6,
    },
  },
  // Fabric
  {
    categoryType: 'Fabric',
    type: 'ToppleCotton',
    suppressionValue: 10,
    name: {
      en: 'ToppleCotton',
      ja: 'トップル木綿',
    },
    standardValue: {
      sharp: 18,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 9,
      slash: 9,
      thrust: 9,
      magic: 9,
    },
    elementResist: {
      wisp: 6,
      shade: 8,
      dryad: 6,
      aura: 10,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 6,
    },
  },
  {
    categoryType: 'Fabric',
    type: "Sultan'sSilk",
    suppressionValue: 10,
    name: {
      en: 'Sultan',
      ja: 'サルタン絹布',
    },
    standardValue: {
      sharp: 28,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 14,
      slash: 14,
      thrust: 14,
      magic: 14,
    },
    elementResist: {
      wisp: 6,
      shade: 8,
      dryad: 6,
      aura: 10,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 6,
    },
  },
  {
    categoryType: 'Fabric',
    type: 'JuddHemp',
    suppressionValue: 10,
    name: {
      en: 'JuddHemp',
      ja: 'ジャドヘンプ',
    },
    standardValue: {
      sharp: 38,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 19,
      slash: 19,
      thrust: 19,
      magic: 19,
    },
    elementResist: {
      wisp: 10,
      shade: 6,
      dryad: 6,
      aura: 10,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 6,
    },
  },
  {
    categoryType: 'Fabric',
    type: 'AltenaFelt',
    suppressionValue: 10,
    name: {
      en: 'AltenaFelt',
      ja: 'アルテナフェルト',
    },
    standardValue: {
      sharp: 48,
      heavy: 1,
      force: 1,
      tech: 1,
      strike: 24,
      slash: 24,
      thrust: 24,
      magic: 24,
    },
    elementResist: {
      wisp: 7,
      shade: 7,
      dryad: 7,
      aura: 9,
      salamander: 10,
      gnome: 7,
      jinn: 7,
      undine: 6,
    },
  },
  // Aerolite
  {
    categoryType: 'Aerolite',
    type: 'JacobiniRock',
    suppressionValue: 16,
    name: {
      en: 'JacobiniRock',
      ja: 'ジャコビニ隕石',
    },
    standardValue: {
      sharp: 15,
      heavy: 11,
      force: 22,
      tech: 24,
      strike: 15,
      slash: 13,
      thrust: 18,
      magic: 24,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 10,
      aura: 7,
      salamander: 7,
      gnome: 8,
      jinn: 9,
      undine: 8,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'HalleyRock',
    suppressionValue: 16,
    name: {
      en: 'HalleyRock',
      ja: 'ハレー隕石',
    },
    standardValue: {
      sharp: 20,
      heavy: 15,
      force: 30,
      tech: 32,
      strike: 20,
      slash: 18,
      thrust: 24,
      magic: 32,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 10,
      aura: 7,
      salamander: 7,
      gnome: 8,
      jinn: 9,
      undine: 8,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'AnkhRock',
    suppressionValue: 16,
    name: {
      en: 'AnkhRock',
      ja: 'アンク隕石',
    },
    standardValue: {
      sharp: 25,
      heavy: 18,
      force: 37,
      tech: 40,
      strike: 25,
      slash: 22,
      thrust: 30,
      magic: 40,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 10,
      aura: 7,
      salamander: 7,
      gnome: 8,
      jinn: 9,
      undine: 8,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'VinekRock',
    suppressionValue: 16,
    name: {
      en: 'VinekRock',
      ja: 'ヴィネック隕石',
    },
    standardValue: {
      sharp: 30,
      heavy: 22,
      force: 45,
      tech: 48,
      strike: 30,
      slash: 27,
      thrust: 36,
      magic: 48,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 10,
      aura: 7,
      salamander: 7,
      gnome: 8,
      jinn: 9,
      undine: 8,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'TuttleRock',
    suppressionValue: 16,
    name: {
      en: 'TuttleRock',
      ja: 'タトル隕石',
    },
    standardValue: {
      sharp: 35,
      heavy: 26,
      force: 52,
      tech: 56,
      strike: 35,
      slash: 31,
      thrust: 42,
      magic: 56,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 10,
      aura: 7,
      salamander: 7,
      gnome: 8,
      jinn: 9,
      undine: 8,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'NemesisRock',
    suppressionValue: 16,
    name: {
      en: 'NemesisRock',
      ja: 'ネメシス隕石',
    },
    standardValue: {
      sharp: 40,
      heavy: 30,
      force: 60,
      tech: 64,
      strike: 40,
      slash: 36,
      thrust: 48,
      magic: 64,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 10,
      aura: 7,
      salamander: 7,
      gnome: 8,
      jinn: 9,
      undine: 8,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'BiellaRock',
    suppressionValue: 16,
    name: {
      en: 'BiellaRock',
      ja: 'ビエラ隕石',
    },
    standardValue: {
      sharp: 45,
      heavy: 33,
      force: 67,
      tech: 72,
      strike: 45,
      slash: 40,
      thrust: 54,
      magic: 72,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 10,
      aura: 7,
      salamander: 7,
      gnome: 8,
      jinn: 9,
      undine: 8,
    },
  },
  {
    categoryType: 'Aerolite',
    type: 'SwifteRock',
    suppressionValue: 16,
    name: {
      en: 'SwifteRock',
      ja: 'スウィフト隕石',
    },
    standardValue: {
      sharp: 50,
      heavy: 37,
      force: 75,
      tech: 80,
      strike: 50,
      slash: 45,
      thrust: 60,
      magic: 80,
    },
    elementResist: {
      wisp: 7,
      shade: 8,
      dryad: 10,
      aura: 7,
      salamander: 7,
      gnome: 8,
      jinn: 9,
      undine: 8,
    },
  },
  // Miscellaneous
  {
    categoryType: 'Miscellaneous',
    type: 'Adamantite',
    suppressionValue: 20,
    name: {
      en: 'Adamantite',
      ja: 'アダマンタイト',
    },
    standardValue: {
      sharp: 62,
      heavy: 46,
      force: 93,
      tech: 99,
      strike: 62,
      slash: 31,
      thrust: 93,
      magic: 62,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 8,
      jinn: 8,
      undine: 8,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'Fullmetal',
    suppressionValue: 20,
    name: {
      en: 'Fullmetal',
      ja: 'フルメタル',
    },
    standardValue: {
      sharp: 55,
      heavy: 41,
      force: 68,
      tech: 66,
      strike: 44,
      slash: 27,
      thrust: 99,
      magic: 27,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 8,
      jinn: 8,
      undine: 8,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'Coral',
    suppressionValue: 12,
    name: {
      en: 'Coral',
      ja: 'サンゴ',
    },
    standardValue: {
      sharp: 18,
      heavy: 21,
      force: 14,
      tech: 12,
      strike: 23,
      slash: 9,
      thrust: 32,
      magic: 9,
    },
    elementResist: {
      wisp: 9,
      shade: 6,
      dryad: 7,
      aura: 7,
      salamander: 9,
      gnome: 7,
      jinn: 9,
      undine: 5,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'TortoiseShell',
    suppressionValue: 20,
    name: {
      en: 'TortoiseShell',
      ja: '甲羅',
    },
    standardValue: {
      sharp: 26,
      heavy: 31,
      force: 20,
      tech: 18,
      strike: 33,
      slash: 13,
      thrust: 46,
      magic: 13,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 9,
      aura: 7,
      salamander: 9,
      gnome: 8,
      jinn: 9,
      undine: 7,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'Shell',
    suppressionValue: 14,
    name: {
      en: 'Shell',
      ja: '貝殻',
    },
    standardValue: {
      sharp: 20,
      heavy: 24,
      force: 16,
      tech: 14,
      strike: 26,
      slash: 10,
      thrust: 36,
      magic: 10,
    },
    elementResist: {
      wisp: 8,
      shade: 7,
      dryad: 9,
      aura: 8,
      salamander: 9,
      gnome: 7,
      jinn: 9,
      undine: 6,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'Emerald',
    suppressionValue: 8,
    name: {
      en: 'Emerald',
      ja: 'エメラルド',
    },
    standardValue: {
      sharp: 2,
      heavy: 2,
      force: 2,
      tech: 2,
      strike: 1,
      slash: 1,
      thrust: 1,
      magic: 50,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 8,
      jinn: 8,
      undine: 8,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'Pearl',
    suppressionValue: 8,
    name: {
      en: 'Pearl',
      ja: 'パール',
    },
    standardValue: {
      sharp: 2,
      heavy: 2,
      force: 2,
      tech: 2,
      strike: 1,
      slash: 1,
      thrust: 1,
      magic: 50,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 8,
      jinn: 8,
      undine: 8,
    },
  },
  {
    categoryType: 'Miscellaneous',
    type: 'LapisLazuli',
    suppressionValue: 8,
    name: {
      en: 'LapisLazuli',
      ja: 'ラピスラズリ',
    },
    standardValue: {
      sharp: 2,
      heavy: 2,
      force: 2,
      tech: 2,
      strike: 1,
      slash: 1,
      thrust: 1,
      magic: 50,
    },
    elementResist: {
      wisp: 8,
      shade: 8,
      dryad: 8,
      aura: 8,
      salamander: 8,
      gnome: 8,
      jinn: 8,
      undine: 8,
    },
  },
] as const;
